"""
Export utilities for VideoMind AI.

Provides helper functions for exporting
AI-generated reports and transcripts.
"""

from io import BytesIO
import re

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)


# Helpers

def sanitize_filename(name: str) -> str:
    """
    Convert a title into a filesystem-safe filename.
    """

    name = name.lower()

    name = re.sub(r"[^\w\s-]", "", name)

    name = re.sub(r"\s+", "_", name)

    return name


# TXT Export

def generate_txt(text: str) -> bytes:
    """
    Return UTF-8 encoded TXT bytes.
    """

    return text.encode("utf-8")


def generate_chat_txt(messages: list) -> bytes:
    """
    Export chat history as a TXT file.
    """

    if not messages:
        return b"No chat history available."

    lines = []

    lines.append("VideoMind AI - Chat History")
    lines.append("=" * 60)
    lines.append("\n")

    for message in messages:

        role = (
            "User"
            if message["role"] == "user"
            else "Assistant"
        )

        lines.append(f"{role}:\n")
        lines.append(message["content"])
        lines.append("\n")
        lines.append("-" * 60)
        lines.append("\n\n")

    return "".join(lines).encode("utf-8")


# PDF Export

def generate_pdf(result: dict) -> bytes:
    """
    Generate a professional PDF report.
    """

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    # Cover

    story.append(
        Paragraph(
            "🎬 <b>VideoMind AI Report</b>",
            styles["Title"],
        )
    )

    story.append(Spacer(1, 20))

    # Title

    story.append(
        Paragraph(
            "<b>Video Title</b>",
            styles["Heading2"],
        )
    )

    story.append(
        Paragraph(
            result["title"],
            styles["BodyText"],
        )
    )

    story.append(Spacer(1, 18))

    # AI Report

    story.append(
        Paragraph(
            "<b>AI Report</b>",
            styles["Heading2"],
        )
    )

    report = (
        result["summary"]
        .replace("\r\n", "\n")
        .replace("\n", "<br/>")
    )

    story.append(
        Paragraph(
            report,
            styles["BodyText"],
        )
    )

    story.append(Spacer(1, 30))

    # Footer

    story.append(
        Paragraph(
            "<i>Generated by VideoMind AI</i>",
            styles["Italic"],
        )
    )

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf